
###
GET http://localhost:2000/patient-service/patient/getall
Authorization: Bearer 
###

POST http://localhost:2000/auth-service/auth/create
Content-Type: application/json

{
    "username": "data",
    "id": 34,
    "password": "memer"
}

###

GET http://localhost:3000/authH/login

###

POST http://localhost:2000/auth-service/auth/refresh
Content-Type: application/json

{
    "token": ""
}

###

DELETE http://localhost:2000/auth-service/auth/delete
Authorization: Bearer 