# 

POST http://localhost:2000/admin-service/appointment/create
Content-Type: application/json

{
    "title": "new",
    "content": "iam on my dieria",
    "status": "pending"
}

###

    # "service-auth": "nest start --watch auth",
    # "service-admin": "nest start --watch admin"

GET http://localhost:2000/admin-service/appointment/get

###

DELETE http://localhost:3001/notes/delete?id=6654c8cde055e5c8c5b0a122