
###
GET http://localhost:2000/patient-service/authH/login
# Authorization: Bearer 
###

POST http://localhost:3000/authH/login
Content-Type: application/json

{
    "name": "data",
    "password": "memer"
}

###

POST http://localhost:3000/authH/signup
Content-Type: application/json

{
    "name": "data",
    "email": "dolla@gmail.com",
    "password": "memer"
}

###

GET http://localhost:3001/patient/getall

###

GET http://localhost:3000/authZ/status
Authorization: Bearer 

###

POST http://localhost:2000/auth-service/auth/refresh
Content-Type: application/json

{
    "token": ""
}

###

DELETE http://localhost:2000/auth-service/auth/delete
Authorization: Bearer 